name: Installing Python
on: [push]
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        py-version: 
          - 3.7
          - 3.8
          - 3.9
        os: 
          - macos-12
          - ubuntu-latest
          - windows-latest
        exclude:
          - os: macos-12
          - py-version: 3.9
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.py-version }}'
        